#!/bin/sh

print_help() {
	echo ""
	echo "FreeRADIUS plugin install:"
	echo ""
	echo "commands:"
	echo "	help:			print commands help"
	echo "	fr:		        install FreeRADIUS plugin"
	echo ""
}

install_freeradius() {
	pkg install ${2}
	cp -pf /usr/local/opnsense/service/templates/OPNsense/Freeradius/rc-radiusd /usr/local/etc/rc.d/radiusd
	chmod +x /usr/local/etc/rc.d/radiusd

	/usr/local/etc/rc.d/radiusd stop
	rm -f /usr/local/etc/raddb/freeradius.db
	/usr/local/etc/rc.d/radiusd restart      
}

case ${1} in
	fr)
        install_freeradius
		;;			
	help)
		print_help
		;;
	*)
		print_help
		;;		
esac

