PLUGIN_NAME=		freeradius-captiveportal
PLUGIN_VERSION=		2.0.0
PLUGIN_COMMENT=		RADIUS Authentication, Authorization and Accounting Server
PLUGIN_DEPENDS=		freeradius3
PLUGIN_MAINTAINER=	reza.ebrahimi.dev@gmail.com

.include "../../Mk/plugins.mk"
